# Generated by Django 4.1.7 on 2023-12-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch9app', '0004_share_holders'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_holders',
            name='share_holders_rent',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
