# Generated by Django 4.1.7 on 2023-03-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='emp_role',
            new_name='role',
        ),
    ]
