# Generated by Django 4.1.7 on 2023-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pg1_regform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg1_regform',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
