# Generated by Django 4.1.7 on 2023-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pg1_regform_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg1_regform',
            name='self_mob_no',
            field=models.BigIntegerField(),
        ),
    ]
