# Generated by Django 4.1.7 on 2023-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pg3_regform_pg3_rooom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg1_rooom',
            name='roon_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pg2_rooom',
            name='roon_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pg3_rooom',
            name='roon_no',
            field=models.CharField(max_length=20),
        ),
    ]
